[package]
name = "mvencode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"

# json
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
base64 = "0.21.6"